apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{
    dict "auths" (dict
      "https://index.docker.io/v1/" (dict
        "username" .Values.image.username
        "password" .Values.image.password
        "auth" (printf "%s:%s" .Values.image.username .Values.image.password | b64enc)
      )
    )
    | toJson
    | b64enc
  }}
