---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ms-d3-client-docker-secret
  namespace: d3
spec:
  encryptedData:
    .dockerconfigjson: AgCs1VPwQgHfVjGuR072e3hxFtDUp8WinJtLK11jxNnVg4tWQV05Ma2k86nz6CjomT2DsEmtAuLT4A0ulwqA9JJkm+qzclPvvs/ClyBt2JypGQW5duewpLbFSkxX00MwEn4/0HE9d2oo02Gax3ruEzRxJ6Hb1Np2CqhfvWrYMMaqPjgfLPs3JlXBxprqpjuXFMadrEu+R6iEuaCyYbqr9t5QxVMZWgP/c5OKXBddMVVecRXUQ0WePpbX3qR5OZm0BO5eUhyyxEvMNO9PM1cGHv6ea0oN0woZXWlxtO5rjfSq81lncGiM4nA7m4cAtubIy6i7XRFcnZm07qTEmafB+ocs8HGYJ1Inrh6ND1AOOo7sL7achsIxFbY8HwokEMjzhtYAQlRg88cs9Jk+aVmrOlj91chjLzFinO+KhDLAOsA/pUQNnH3gzNNFp1qoym5t4XiUttRAp7Pxx0r5fvrCnXxeNP3GEMEUwlBeLzjIWXDD1zxv4/Rz82ZY5qt1zEWLIgh9NNvr8HJZtww8YFBVoLNm1998a0wWGbx83+eIInCTaJt4cP9RjnfgOh+Z/jISbEHeQ+7OQDDYnEKT8Mv+d/o0o6DEzP/cC/KVQrKxoTDJ+w4VGsKGJldMsnQ1X6/a4EMwFMqTnRexLY0/or77b5nYMWgICX5+0ikthnoL3NpVY93bSfrxyPRAkifkfQ1MGT8p1A5DSsX3IH3YTnwBlwQOAMJDk3t3W4khw9VJ/8Ak8Ja4/1XSkQgfdS2ltsQ9xITpVKLsC7QrUJ/3xBhSYgYwZXf99GSkhVqa7ifj11gUAqv5bgTVRsTqgfWV6aLj2UIElNX2SYmEKgwukvKb0OFKPwhlkNN0YCkk06lntS88tHxHRBgiEDRFASqaFk9EF0lNvjd8iWmKA1GZfGPEW4XUSv1ynLZCx6OxBe+/HFv1TgpTIvn+BgU+
  template:
    metadata:
      name: ms-d3-client-docker-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
