---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ms-d3-client-secret
  namespace: d3
spec:
  encryptedData:
    DB_PASSWORD: AgAe/4Nol6Sdg2LHT46BcEE9PugTl9Y+JlQ4bBtr8EkgMrmnbtTotO+pzmRULMT0CTqtU0s2uFdwuMUDhWI0IjlgcJz6MhA2G4FxkOp/CyPuS5Gd0RZYXjzXV/7qZNPKiCdpNJuWWG04hVKi8A2Yaajpc2wfEEtksp+ibyL2PVE2+ez91JNWAa/9iKjG3ejevFRhmern6s1XM0KrDzHqV1fQfngnssbUUFuno9+sdMdo4pCEwCV47cydtpo+/bQR+BEUQXUb0S7eeZDxjByheb9bvw2AHjLikh0SV/+lAn03buw7wKEAeV5oHKOTh9oZc0P53f9vqGjL89uiLm65MFM28/whqeNuW8SbkzKR62fRv2l/udJLufxCEZY3rN+9Iixi1EC3pLb0aMfjA/72UWJH4DpRF+95IcNPpuZIJ7vfXcJOQgjTTpi1wr1bgnWCFf2JJm0cusDo2UtMT2FCm3evha3liqb2rt/Nhp89r5h7gC5XDQ3VuhO6wR7nYFlPvbKgt9oQjBaeClo0N52hcLnGtQbAS3MaT5JurSCwn8s3YLMD1+pqXQjiq3l8YymDrcUYQKPZyC4fgQyq4balJAWHFzDOKvdIDIQLLFyf1N7UakajaGtEFvWWKpupxSEPcIxcpXcaxbEb87fFsG1zXaAi+Wn89O0W1gm6HIf76AJIhhPqpP1437tEXTea5v7LxvlFcaMZjRs=
    DB_USERNAME: AgAQzynsASG6Y1GYr7HIMFEg3FgG2EtNw18/8MBsqbCFdszk3Icz03gAVzpDX+1AZMQCN4FwWRNPZ1zvnYPFlYyDcaTUdqqKRM9xI/TrWuwMTmHbLPrxxHLG5i8dTq9QsIzMCn8y/SObrXO6shSuvgLKcOJclHorGMezoehZoX6qKP81H0ne/RyoP5pDqUmtHs9OSKyJk9RpDQSVk3/4svhapy5SBz6D8TPL+6tqXCs0ZXaBhWHuIBYpXvoGfh5ePLs4ok/tm+ckZD3J8IKZliIl8muN0xPPX2Yk7zOo+6gqcen+kB24HMLCPakGUuFgBDe6PZ3BBxEk5I1OMllw+nXPMDo2YXCquR71YdogHRVmq59/xInSH9NJx5xAZnOvQ4ZlHjhdwzpJQGH5DYbYNGpBMG5KHQUlf4iD9OSPfFiHZnfoVeHMjNijxZkvvu5J+BIdj5kQZuW+RltXRWvVQo937NWHlE7CigEs91ZqLgzmZUbNbRRN1sSdZY+ADu3yYUHUA30qaMiQ7oWdsqtxo9wtDswm6iODIiQmS333gFBFXdyyQe5RFIXOt6rs49/3pBIW9eFxtP2tTabanib7xrBY7+kR9IazNdjymJiIv0hw83/durNYuzsLMxzUg2BJznf4RQkwlEX9qAx25zqsFuPqlZw28Fbvpvid2Qmi4xk55XRrkGVDauvn3kkBOSMty1iebV2IN9U=
  template:
    metadata:
      name: ms-d3-client-secret
      namespace: default
