apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.config.db.username | quote }}
  DB_PASSWORD: {{ .Values.config.db.password | quote }}
