Vagrant.configure("2") do |config|
  # VARIABLES
  BOX_NAME   = "ubuntu/jammy64"
  BOX_MEMORY = 4096
  BOX_CPUS   = 4
  VM_NAME    = "k3s-master"
  MASTER_IP  = "192.168.1.100"

  # CONFIG
  config.vm.define VM_NAME do |master|
    master.vm.box = BOX_NAME
    master.vm.hostname = VM_NAME

    master.vm.network "public_network", ip: MASTER_IP

    master.vm.provider "virtualbox" do |vb|
      vb.name   = VM_NAME
      vb.cpus   = BOX_CPUS
      vb.memory = BOX_MEMORY
    end
  end
end