apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}-secret
type: Opaque
stringData:
  S3_URL: {{ .Values.common.s3.url | quote }}
  S3_LOGIN: {{ .Values.common.s3.login | quote }}
  S3_PASSWORD: {{ .Values.common.s3.password | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.password | quote }}