apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |
    server:
      http_listen_port: 9009


    common:
      storage:
        backend: s3
        s3:
          endpoint: ${S3_URL}
          access_key_id: ${S3_LOGIN}
          secret_access_key: ${S3_PASSWORD}
          insecure: true

    blocks_storage:
      s3:
        bucket_name: mimir-blocks

    ruler_storage:
      s3:
        bucket_name: mimir-rules

