image:
  repository: d3fix4m/ms-d3-client
  tag: 1.0.0.0.0.24
server_port: '8080'
db_url: jdbc:postgresql://d3-client-db-0.d3-client-db-service.db.svc.cluster.local:5432/client
db_username: client
db_password: client
kafka_bootstrap_servers: kafka-0.kafka-headless.kafka.svc.cluster.local:9092
