apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
spec:
  serviceName: tempo
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: "{{ .Values.tempo.image.repository }}:{{ .Values.tempo.image.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
            - "-config.expand-env=true"
          ports:
            - containerPort: 3200
              name: http
            - containerPort: 4317
              name: grpc
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-secret
          volumeMounts:
            - name: data
              mountPath: /var/tempo
            - name: config
              mountPath: /etc/tempo
      volumes:
        - name: config
          configMap:
            name: tempo-config
            items:
              - key: tempo.yaml
                path: tempo.yaml
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hostpath
        resources:
          requests:
            storage: '1Gi'