apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:12.4.0
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: d3fix4m
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: d3d3
            - name: GF_SERVER_ROOT_URL
              value: "http://monitoring.d3.local/grafana/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            - name: datasource
              mountPath: etc/grafana/provisioning/datasources
              readOnly: false
      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: "local-path"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi