- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install required packages
  apt:
    name:
      - curl
      - nano
    state: present

- name: Disable ufw firewall
  systemd:
    name: ufw
    enabled: no
    state: stopped