apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      path_prefix: /loki

    schema_config:
      configs:
        - from: 2020-05-15
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      aws:
        s3: s3://${S3_LOGIN}:${S3_PASSWORD}@${S3_URL}/loki
        insecure: true