Vagrant.configure("2") do |config|
  # VARIABLES
  BOX_NAME      = "ubuntu/jammy64"
  BOX_MEMORY    = 4096
  BOX_CPUS      = 4
  BASE_VM_NAME  = "k3s-worker-"
  BASE_MASTER_IP= "192.168.1.20"
  VM_COUNT      = 1

  # CONFIG
  (1..VM_COUNT).each do |i|
    vm_name = "#{BASE_VM_NAME}#{i}"

    config.vm.define vm_name do |worker|
      worker.vm.box = BOX_NAME
      worker.vm.hostname = vm_name

      worker.vm.network "public_network", ip: "#{BASE_MASTER_IP}#{i}"

      worker.vm.provider "virtualbox" do |vb|
        vb.name   = vm_name
        vb.cpus   = BOX_CPUS
        vb.memory = BOX_MEMORY
      end
    end
  end
end