apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      containers:
        - name: {{.Release.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-config
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              port: {{.Values.server_port}}
              path: /actuator/health/readiness
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              port: {{.Values.server_port}}
              path: /actuator/health/liveness
            initialDelaySeconds: 90
            periodSeconds: 5
            failureThreshold: 3

