---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ms-d3-client-docker-secret
  namespace: d3
spec:
  encryptedData:
    .dockerconfigjson: AgBhVZ55uP6T1B0WBR/4QopRaObmH03G52faGwz2dyvzmVZ4CCgic0etmF2SyawgogZ+6MdTBlCtGy+U59iJjpSmz5QbFceoTaC8o330+WhOLPVDZKOqeCXbOHf1TwRLXCRJbF+HY4O3GZqlFVwj6vChyul1HoRIBhCRKZNK4+K2aaJIYJc5qIjjNu7Mk/aHIpx/36Sn6VBmbYBTHtddF5m5O33+cmsJllXesYplzWQqvn0ytQnKZLJF5kcaLH8/26ntKYLJs1Zc7qC/nY/sirqr4xd6tOJxu9bnYWE2+ykjATVlwAEvB7mnIfdzOHQ7QTjbxcnJDyuRnPifHNVpfvoo6uf7y2Jq0bNvmmdf6Mh9w/RIrugzKlGGhbiREEh4gAxJlJ7+oxKJi92veOqWVXN9uy89OxjYu/1sNiz2W3ehYDiIr9DbUWP736WcvulCG3xRbE6K9ya85gosc9ioFLYO8PnfKwLPlMz5TC76BBTM/t32TeFGlg263XirtVIkY3PDMCcOWhqW7HlOgVfJdULwXsy7XJJxs/yiSOZKGRjYT8S2MDagKvdN7OrraJhb/b5hJnI9iTe48aj//qF0b6Ce8e7ed8ZZVhtKuPc6+GG/YlVzruiq95+5yIaS2DPr63sPc16YZRE7bgNY8Rhd4/zB1w8+wUpig8cm4bQDvfkW68y4ooG4gOUPhe/53PruL1z+//+i5Br7Tq4gd43ms99YVsrhNpKIA0NV5EQVOGn++AXzaqKvEzRgoFPJyiXRqerI5K50QIbPtmnyHG1kUSLEFjQUGZgl2OekFGXkHYlyUfmrL9g7Q+mCN5MbSNO6LnwueeeoYqNQt1CA1OheVyoNvBOslmsSEW8Yb/5PielCBuBt88ATUxhGItyXQyZHKLOs5HaUQyzXhvDFfEECAJC7CmGVR2dzo1dIUH/cpMEmpd1d823lE2F7Uz5R3OTf
  template:
    metadata:
      name: docker-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
