---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgAEl+AEg7GU1N5VWPWPXq/67/g+pXy6Bl3QHjSoveGdY0P0VLw+84C2wyq3opsPga54u3Un/HSIztmSbe/9/3/C48oO9N2cTMQTJitDH0Lh5rSxdleyn3saeYo5UB1SlPiWm0+OfTdEBElVF1MwuuF5WfPsv6LYZMiKic3Z5nvBSgG+QP+ZiV+XYHb1qKIrnL/x9KV0+u0n/UBkYtfYUWlny5nFCBjF+HBIygNR7JQz8ID0txS5DuDH+UDmRsYsBy94UfGdZvLMGForWtX4ATPVNnCAGJANIjFxRlYan+EDCyeLR4VoGi05E9uFjJRejmDMeLHJG02a9Le9I/9gJMaOK5/ZHIJq/shtvEWCysNmH7FkWcIcUT+jadIZHnjQlCt9qmdJVsTbN/eifFQvdqKm1/eE+wnpIm8NPRg8HIOy592cMJHO3aqnLMnlSA9ZWvKbTt0W8W5NJ3NvM6QTO5NZVPARptZSenkIM+wuIrqKE4ugx+uw1uKLWWm2p4gacICix2lNwJy5ng+22s8Zqom9WtL1rex/rU7PM57a4eth3Xv2mJjrzGckCVNaLIbEAc8znNuT3I1fDsy+5lbzCRWx4FymqMS6YVhxVvgdpYqwB0lTHdxSJXO/D7JCDN8dgC18SniWWmm6U1Ua32+5r/HGYXVa9gQqWlQACd7TcQTxzieQLXd7YJddyTvdzEd7Bl+07Zynu78=
    DB_USERNAME: AgA72c7NhLgF/Rh6nPLuUgaygWwPq0vLdl4WgMdeUZQHVQxpCanyHCl6tE7HPUwsv4+v7uCn3XaTvuXym+ZzGNZheQgX95NQS5hJnOScNeMu4ngjD9Q3kQA6Nbxcy0IAbphgEo9rjHu+5V2XMxdyJ4tNSV+10mYxzpgVgN4zzA+1RJzvuJnFPcgoh8XRs2UcTRO01BrS/Xgpf1GFOBTFuxYEXd+w1TifQg+Mn5RYALGj/7DQbJ41YCpX3SkDeYvLLAQasmG2a7bv7nmP9Ga+VLxgjDNZ7wS8Dy80KbMcebxXy4K1eE6T41LwMawPQGJNQdhY5NrerHlxyzdj1ibjRfidCmNeE36mKYT3fxf956l7eYPg0OLDM/pFxgT1W3YpGeD2/5TNQs2hz7hJ9F/65vsJl8mL6+XM2WvW3VkY0R6lew4UZ6pt+ZPc6dhB2HT3VGnL+r321DpP9Br88dp5EFybZaUGgvw+Ubns1nqIpl6bv+Mh2WIqJUB3AOoOCz+3wYAmpW5frpPPxFkKD2i+Nv81QdU8mqWc3UZ3WtN+1nG8Kr2waDVShA9ADfZxVQMDyL2V0IMNazkRfrallrpjuFsVk2UL4n0Gyi/hpSPI4aC/lFxFzdJQtKiDDRqUhJOQrfMBkpCnjyK2zNwSFIH5esG5X0pCpf/zMMhEC7eL4iLFLhMFXJSq97bUJ+kB2TVzdnMtXIZ4HKE=
  template:
    metadata:
      name: secret
      namespace: default
